# Generated by Django 4.1.1 on 2022-09-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%d/%m/%Y/')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('categor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='strangecars.categories')),
            ],
            options={
                'verbose_name': 'Странная машина',
                'verbose_name_plural': 'Странные машины',
                'ordering': ['-time_create', 'title'],
            },
        ),
    ]
